export const mockTheme = {
  mode: 'light' as const,
  colors: {
    primary: '#FF6B6B',
    primaryLight: '#FFE0E0',
    primaryDark: '#CC5555',
    secondary: '#4ECDC4',
    accent: '#FFD93D',
    background: '#FFFFFF',
    backgroundCard: '#F8F9FA',
    backgroundElevated: '#FFFFFF',
    textPrimary: '#1A1A2E',
    textSecondary: '#6B7280',
    textMuted: '#9CA3AF',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    info: '#3B82F6',
    border: '#E0E0E0',
    softBackground: '#EFD6AC',
    textOnPrimary: '#FFFFFF',
    traitUnknown: '#F3F4F6',
    traitUnknownText: '#6B7280',
    traitYes: '#D1FAE5',
    traitYesText: '#065F46',
    traitNo: '#FEE2E2',
    traitNoText: '#991B1B',
  },
  typography: {
    fontSize: {
      xs: 12,
      sm: 14,
      base: 16,
      lg: 18,
      xl: 20,
      '2xl': 24,
      '3xl': 30,
      '4xl': 36,
    },
    fontFamily: {
      regular: 'System',
      medium: 'System',
      semibold: 'System',
      bold: 'System',
    },
  },
  spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32 },
  borderRadius: { sm: 4, md: 8, lg: 12, xl: 16, full: 9999 },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.07,
      shadowRadius: 4,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 6,
    },
  },
};

export const mockThemeContext = {
  theme: mockTheme,
  mode: 'system' as const,
  setMode: jest.fn(),
  effectiveMode: 'light' as const,
};
